/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_utils_DiagnosisNDK */

#ifndef _Included_ecg
#define _Included_ecg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_utils_DiagnosisNDK
 * Method:    getEcgResult
 * Signature: ([DJI)Lcom/test/objects/HeartRateResult;
 */
JNIEXPORT jobject JNICALL Java_com_test_utils_DiagnosisNDK_getEcgResult
  (JNIEnv *, jclass, jdoubleArray, jlong, jint);

/*
 * Class:     com_test_utils_DiagnosisNDK
 * Method:    getPpgResult
 * Signature: ([DIIIIIIII)Lcom/test/objects/PluseRateP_PP;
 */

jint Java_com_test_utils_DiagnosisNDK_getEcgHeart
  (JNIEnv * env, jclass clazz, jintArray source, jint length, jint s_rate);


void Java_com_test_utils_DiagnosisNDK_getPedo
  (JNIEnv * env, jclass clazz, jbyteArray intdat,jint len, jintArray outData);

float Java_com_test_utils_DiagnosisNDK_getkcal
  (JNIEnv * env, jclass clazz, jint sex,jint hr, jint age,jfloat weight,jfloat time);

#ifdef __cplusplus
}
#endif
#endif
